### ISSUE TITLE
graphical analysis

### ISSUE THREAD

**Issue by manuelkasiske** [manuelkasiske/mutservice#20]
We want to add some graphical evaluations. Ideas are welcome ...

**Comment by j-musca** [comment]
example http://jsfiddle.net/oe2606ww/144/

**Comment by j-musca** [comment]
`Chart.types.Line.extend({
  name: "LineAlt",
  initialize: function(data) {
    Chart.types.Line.prototype.initialize.apply(this, arguments);

    this.originalClear = this.clear;
    this.clear = function() {
      this.originalClear();
      var lengthPerPoint = this.datasets[0].points[1].x - this.datasets[0].points[0].x;
      var heightStart = this.scale.endPoint;
      var heightPerLine = (this.scale.startPoint - heightStart) / 4;
      var numberOfPoints = this.datasets[0].points.length;
      var startPoint = this.datasets[0].points[0].x;
      
      this.chart.ctx.fillStyle = 'rgba(255,24,24,0.8)'; // red     
      this.chart.ctx.fillRect(startPoint, heightStart, lengthPerPoint * numberOfPoints, heightPerLine);
      this.chart.ctx.fillStyle = 'rgba(255, 153, 0,0.8)'; // orange
      this.chart.ctx.fillRect(startPoint, heightStart + heightPerLine, lengthPerPoint * numberOfPoints, heightPerLine);
      this.chart.ctx.fillStyle = 'rgba(51, 153, 255,0.8)'; // blue
      this.chart.ctx.fillRect(startPoint, heightStart + heightPerLine * 2, lengthPerPoint * numberOfPoints, heightPerLine);
      this.chart.ctx.fillStyle = 'rgba(91, 194, 54,0.8)'; // green
      this.chart.ctx.fillRect(startPoint, heightStart + heightPerLine * 3, lengthPerPoint * numberOfPoints, heightPerLine);
    }
  }
});

var data = {
  labels: ["03-04-2016", "03-04-2016", "03-04-2016", "03-04-2016"],
  datasets: [{
    label: "My First dataset",
    fillColor: "rgba(220,220,220,0.1)",
    strokeColor: "rgba(220,220,220,1)",
    pointColor: "rgba(133,133,133,1)",
    pointStrokeColor: "#fff",
    pointHighlightFill: "#fff",
    pointHighlightStroke: "rgba(220,220,220,1)",
    data: [2.3, 2.6, 3, 2.7]
  }]
};

var options = {
	scaleOverride : true,
  scaleSteps : 4,
  scaleStepWidth : 1,
  scaleStartValue : 0,
  scaleLineColor: "rgba(0,0,0,.5)",
}

var ctx = document.getElementById("myChart").getContext("2d");
var myNewChart = new Chart(ctx).LineAlt(data, options);
`

**Comment by j-musca** [comment]
Chart.types.Line.extend({
  name: "LineAlt",
  initialize: function(data) {
    Chart.types.Line.prototype.initialize.apply(this, arguments);

    this.originalClear = this.clear;
    this.clear = function() {
      this.originalClear();
      var lengthPerPoint = this.datasets[0].points[1].x - this.datasets[0].points[0].x;
      var heightStart = this.scale.endPoint;
      var heightPerLine = (this.scale.startPoint - heightStart) / 4;
      var numberOfPoints = this.datasets[0].points.length;
      var startPoint = this.datasets[0].points[0].x;
      
      this.chart.ctx.fillStyle = 'rgba(255,24,24,0.8)'; // red     
      this.chart.ctx.fillRect(startPoint, heightStart, lengthPerPoint * numberOfPoints, heightPerLine);
      this.chart.ctx.fillStyle = 'rgba(255, 153, 0,0.8)'; // orange
      this.chart.ctx.fillRect(startPoint, heightStart + heightPerLine, lengthPerPoint * numberOfPoints, heightPerLine);
      this.chart.ctx.fillStyle = 'rgba(51, 153, 255,0.8)'; // blue
      this.chart.ctx.fillRect(startPoint, heightStart + heightPerLine * 2, lengthPerPoint * numberOfPoints, heightPerLine);
      this.chart.ctx.fillStyle = 'rgba(91, 194, 54,0.8)'; // green
      this.chart.ctx.fillRect(startPoint, heightStart + heightPerLine * 3, lengthPerPoint * numberOfPoints, heightPerLine);
    }
  }
});

var data = {
  labels: ["03-04-2016", "03-04-2016", "03-04-2016", "03-04-2016"],
  datasets: [{
    label: "My First dataset",
    fillColor: "rgba(220,220,220,0.1)",
    strokeColor: "rgba(220,220,220,1)",
    pointColor: "rgba(133,133,133,1)",
    pointStrokeColor: "#fff",
    pointHighlightFill: "#fff",
    pointHighlightStroke: "rgba(220,220,220,1)",
    data: [2.3, 2.6, 3, 2.7]
  }]
};

var options = {
	scaleOverride : true,
  scaleSteps : 4,
  scaleStepWidth : 1,
  scaleStartValue : 0,
  scaleLineColor: "rgba(0,0,0,.5)",
}

var ctx = document.getElementById("myChart").getContext("2d");
var myNewChart = new Chart(ctx).LineAlt(data, options);

**Comment by j-musca** [comment]
https://gist.github.com/j-musca/861cf2cf243996163e38e89224399f97
