### ISSUE TITLE
Echo does not work with go 1.6

### ISSUE THREAD

**Issue by manuelkasiske** [manuelkasiske/mutservice#9]
```bash
# github.com/labstack/echo/engine/fasthttp
github.com/labstack/echo/engine/fasthttp/header.go:21: h.RequestHeader.Add undefined (type *fasthttp.RequestHeader has no field or method Add)
github.com/labstack/echo/engine/fasthttp/header.go:56: h.ResponseHeader.Add undefined (type *fasthttp.ResponseHeader has no field or method Add)
```

**Comment by j-musca** [comment]
Remove all directorires from 
$GOPATH/pkg/linux_amd64 
$GOPATH/src/github.com
$GOPATH/src/golang.org

and then reinstall the deps

go get github.com/asdine/storm
go get github.com/ddliu/go-httpclient
go get github.com/labstack/echo/...
go get github.com/nu7hatch/gouuid
go get github.com/robfig/cron

we have to use a good vendor tool for our deps like glide, govendor, etc.
